name: Build Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Options: 'temurin', 'zulu', 'adopt', etc.
          java-version: '17'       # Specify the required JDK version

      # Import GPG Keys
      - name: Import GPG Keys
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$GPG_PUBLIC_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      # Set GPG Passphrase
      - name: Set GPG Passphrase
        run: echo "GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}" >> $GITHUB_ENV

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Sign JAR with GPG
      - name: Sign JAR with GPG
        run: mvn clean deploy -DskipTests -Psign

      # Optional: Archive build artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar
