name: Maven Build and GPG Sign

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Import GPG Keys
      run: |
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        echo "$GPG_PUBLIC_KEY" | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG

    - name: Set GPG Passphrase
      run: echo "GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Sign JAR with GPG
      run: mvn clean deploy -DskipTests -Psign

    - name: Upload JAR to Maven Repository
      if: success()
      run: |
        mvn deploy:deploy-file \
          -Dfile=target/iop-api-sdk-1.3.5-ae.jar \
          -Durl=https://your.maven.repo/repository/maven-releases/ \
          -DrepositoryId=your-repository-id \
          -DpomFile=pom.xml \
          -Dfiles=target/iop-api-sdk-1.3.5-ae.jar \
          -Dusername=${{ secrets.MAVEN_USERNAME }} \
          -Dpassword=${{ secrets.MAVEN_PASSWORD }}
