name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK (make sure to use a Java version compatible with your Maven setup)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Set up GPG keys for signing
      - name: Import GPG keys
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$GPG_PUBLIC_KEY" | gpg --batch --import
          echo "passphrase=$GPG_PASSPHRASE" > ~/.gnupg/gpg.conf

      # Set up GPG agent
      - name: Start GPG agent
        run: |
          gpgconf --launch gpg-agent

      # Run Maven build and sign artifacts
      - name: Build and sign artifacts
        run: |
          mvn clean deploy -DskipTests

      # Upload artifacts (if necessary)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/*.jar
