name: Build Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Import GPG Keys
      - name: Import GPG Keys
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$GPG_PUBLIC_KEY" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      # Configure GPG Passphrase
      - name: Configure GPG Passphrase
        run: |
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Build and Sign Artifacts
      - name: Build and Sign Artifacts
        run: mvn clean deploy -DskipTests -Psign -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      # Optional: Upload Artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/*.jar
